"""Add partial unique index for open work items

Revision ID: c295d92760f9
Revises: b2c3d4e5f6a1
Create Date: 2026-05-06 09:27:36.978272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c295d92760f9'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_incident_events_created_at'), 'incident_events', ['created_at'], unique=False)
    op.alter_column('work_items', 'status',
               existing_type=postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='workitemstatus'),
               server_default=None,
               existing_nullable=False)
    op.create_index('uix_work_items_component_open', 'work_items', ['component_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_work_items_component_open', table_name='work_items', postgresql_where=sa.text("status = 'OPEN'"))
    op.alter_column('work_items', 'status',
               existing_type=postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='workitemstatus'),
               server_default=sa.text("'OPEN'::workitemstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_incident_events_created_at'), table_name='incident_events')
    # ### end Alembic commands ###
