apiVersion: 1

datasources:
  - name:      Prometheus
    type:      prometheus
    uid:       prometheus-ims
    access:    proxy
    url:       http://prometheus:9090
    isDefault: true
    editable:  false
    jsonData:
      timeInterval:       "5s"     # Match scrape interval for ims_backend
      queryTimeout:       "60s"
      httpMethod:         POST
      manageAlerts:       true
      prometheusType:     Prometheus
      prometheusVersion:  "2.45.0"
